stages:
  features_application:
    cmd: python ./src/app/modelling/features/application.py
    deps:
    - ./data/application_test.csv
    - ./src/app/modelling/features/application.py
    outs:
    - ./data/features_application_test.csv
  features_bureau:
    cmd: python -u ./src/app/modelling/features/bureau.py
    deps:
    - ./data/bureau.csv
    - ./src/app/modelling/features/bureau.py
    outs:
    - ./data/features_bureau.csv
  features_credit_card_balance:
    cmd: python -u ./src/app/modelling/features/credit_card_balance.py
    deps:
    - ./data/credit_card_balance.csv
    - ./src/app/modelling/features/credit_card_balance.py
    outs:
    - ./data/features_credit_card_balance.csv
  features_installments_payments:
    cmd: python -u ./src/app/modelling/features/installments_payments.py
    deps:
    - ./data/installments_payments.csv
    - ./src/app/modelling/features/installments_payments.py
    outs:
    - ./data/features_installments_payments.csv
  features_previous_application:
    cmd: python -u ./src/app/modelling/features/previous_application.py
    deps:
    - ./data/previous_application.csv
    - ./src/app/modelling/features/previous_application.py
    outs:
    - ./data/features_previous_application.csv
  important_application_train:
    cmd: python ./src/hw5/application_train.py
    deps:
    - ./data/application_train.csv
    - ./src/hw5/application_train.py
    outs:
    - ./data/important_application_train.csv
  important_bureau:
    cmd: python -u ./src/hw5/bureau.py
    deps:
    - ./data/application_train.csv
    - ./data/bureau.csv
    - ./src/hw5/bureau.py
    outs:
    - ./data/important_bureau_train.csv
  important_bureau_balance:
    cmd: python -u ./src/hw5/bureau_balance.py
    deps:
    - ./data/application_train.csv
    - ./data/bureau_balance.csv
    - ./src/hw5/bureau_balance.py
    outs:
    - ./data/important_bureau_balance_train.csv
  important_credit_card_balance:
    cmd: python -u ./src/hw5/credit_card_balance.py
    deps:
    - ./data/application_train.csv
    - ./data/credit_card_balance.csv
    - ./src/hw5/credit_card_balance.py
    outs:
    - ./data/important_credit_card_balance_train.csv
  important_installments_payments:
    cmd: python -u ./src/hw5/installments_payments.py
    deps:
    - ./data/application_train.csv
    - ./data/installments_payments.csv
    - ./src/hw5/installments_payments.py
    outs:
    - ./data/important_installments_payments_train.csv
  important_previous_application:
    cmd: python -u ./src/hw5/previous_application.py
    deps:
    - ./data/application_train.csv
    - ./data/previous_application.csv
    - ./src/hw5/previous_application.py
    outs:
    - ./data/important_previous_application_train.csv
  features_log:
    cmd: python -u ./src/hw_31/hw31.py
    deps:
    - ./data/POS_CASH_balance_plus_bureau-001.log
    - ./src/hw_31/hw31.py
    outs:
    - ./data/log_POS_CASH_balance.csv
    - ./data/log_bureau.csv
  catboost:
    cmd: python -u ./src/app/modelling/hw7_catboost.py
    deps:
    - ./data/application_train.csv
    - ./data/features_application_train.csv
    - ./data/features_bureau.csv
    - ./data/features_credit_card_balance.csv
    - ./data/features_installments_payments.csv
    - ./data/features_previous_application.csv
    - ./src/app/modelling/hw7_catboost.py
    outs:
    - ./data/hw_7_catboost_model.pkl
  random_forest:
    cmd: python -u ./src/app/modelling/hw7_random_forest.py
    deps:
    - ./data/application_train.csv
    - ./data/features_application_train.csv
    - ./data/features_bureau.csv
    - ./data/features_credit_card_balance.csv
    - ./data/features_installments_payments.csv
    - ./data/features_previous_application.csv
    - ./src/app/modelling/hw7_random_forest.py
    outs:
    - ./data/hw_7_random_forest.pkl
